config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'sessions/new'
  root 'sessions#new'
  get '/rule', to: 'static_pages#rule'
  get '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/list', to: 'static_pages#list'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/betting', to: 'betting#new'
  post '/betting', to: 'betting#create'
  delete '/logout', to: 'sessions#destroy'
  get '/winpoint', to: 'winpoint#winpoint'
  post '/winpoint', to: 'winpoint#update'
  get '/groups', to: 'groups#new'
  get '/point_list', to: 'rank#list'
  get '/ranking', to: 'rank#ranking'
  resources :users
end

app/models/betting.rb
class Betting < ApplicationRecord
  belongs_to :user
end

app/controllers/betting_controller.rb
class BettingController < ApplicationController
  
  Total_point = 528
  List_count = 32
  Max_num = 32
  Min_num = 1
  
  def index
  end
  
  def new
    if flash[:user_id] != nil
      @country = Country.all[0]
      @user = User.find(flash[:user_id])
      @betting = Betting.new
      @points = {}
    else
      redirect_to controller: 'sessions', action: 'new'
    end
  end
  
  def create
    user_id = params["betting"]["user_id"]
    @user = User.find(user_id)
    points = point_list(params)
    error_messages = error_message(points)
    if error_messages.length == 0
      Betting.import betting_list(user_id, params)
      flash[:success] = "You are success to bet!!!"
      redirect_to @user
    else
      flash.now[:danger] = error_messages
      @country = Country.all[0]
      @betting = Betting.new
      @points = params
      render :new, :user_id => user_id
    end
  end
  
  def list
  end
  
  def rank
  end
  
  private
  
    def error_message(points)
      messages = []
      if !total?(points, Total_point)
        messages.push("Error! total is not " + Total_point)
      end
      if duplicate?(points)
        messages.push("Error! duplicate value exists!")
      end
      if has_over?(points, Max_num)
        messages.push("Error! max is " + Max_num)
      end
      if has_less?(points, Min_num)
        messages.push("Error! min is " + Min_num)
      end
      return messages
    end

    def total?(pointList, total)
      return pointList.inject(:+) == total
    end
    
    def duplicate?(pointList)
      return pointList.uniq.length != List_count
    end
    
    def has_over?(point_list, max)
      return point_list.max > max
    end
    
    def has_less?(point_list, min)
      return point_list.min < min
    end
    
    def point_list(dict)
      return params.values.map{|val| 
      if val =~ /^[0-9]+$/
        val.to_i
      end
      }.compact
    end
    
    def betting_list(user_id, dict)
      return dict.map{|key,value|
      if value =~ /^[0-9]+$/
        Betting.new(user_id: user_id, country_id: key, bet_point: value)
      end
      }.compact
    end
end

app/helpers/betting_helper.rb
module BettingHelper
end

app/views/betting/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation" >
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg%></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/betting/_form.html.erb
<%= form_for(@betting,url: yield(:url)) do |f| %>
    <% @country.names.each do |name| %>
    <div class="col-md-3">
        <%= f.label :names, name %>
        <% if @points.has_key? name %>
            <%= f.number_field "bet", :value => @points[name], min: 0, max: 32, class: 'form-control', name: name %> 
        <% else %>
            <%= f.number_field "bet", :value => 0, min: 0, max: 32, class: 'form-control', name: name %> 
        <% end %>
    </div>
    <% end %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/betting/new.html.erb
<% provide(:title, "betting") %>
<% provide(:url, betting_path) %>
<% provide(:button_text, "betting") %>
<h1>Betting</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>