config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'sessions/new'
  root 'sessions#new'
  get '/rule', to: 'static_pages#rule'
  get '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/list', to: 'static_pages#list'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/betting', to: 'betting#new'
  post '/betting', to: 'betting#create'
  delete '/logout', to: 'sessions#destroy'
  get '/winpoint', to: 'winpoint#winpoint'
  post '/winpoint', to: 'winpoint#update'
  get '/groups', to: 'groups#new'
  get '/point_list', to: 'rank#list'
  get '/ranking', to: 'rank#ranking'
  resources :users
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer ">
  <small>
    The Worldcup bookmaker</a>
    by Hiroki Ui</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Worldcup bookmaker", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right ul-header">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Rule", rule_path %></li>
        <li><%= link_to "Ranking", '/ranking' %></li>
        <li><%= link_to "List", '/point_list' %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= button_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <% if message_type != "user_id" %>
          <%= content_tag(:div, message,class: "alert alert-#{message_type}") %>
        <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="./footerFixed.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="jumbotron">
      <div class="container">
        <% flash.each do |message_type, message| %>
        <% if message_type != "user_id" %>
        <%= content_tag(:div, message,class: "alert alert-#{message_type}") %>
        <% end %>
        <% end %>
        <%= yield %>
        <footer id="footer" class="footer"></footer>
      </div>
    </body>
  </div>
</html>